#############################################################################
# Makefile for building: blaser_app
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  framework_3.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile framework_3.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/pylon/include -I/usr/include/opencv4/opencv2 -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtSql -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = blaser_app1.0.0
DISTDIR = /home/cat/software/.tmp/blaser_app1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/pylon/lib
LIBS          = $(SUBLIBS) -L/usr/lib/aarch64-linux-gnu -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_features2d -lopencv_flann -lopencv_imgproc -L/opt/pylon/lib -lpylonbase -lpylonutility /opt/pylon/lib/libGenApi_gcc_v3_5_Basler_pylon_v1.so /opt/pylon/lib/libGCBase_gcc_v3_5_Basler_pylon_v1.so /usr/lib/aarch64-linux-gnu/libQt5Widgets.so /usr/lib/aarch64-linux-gnu/libQt5Gui.so /usr/lib/aarch64-linux-gnu/libQt5Sql.so /usr/lib/aarch64-linux-gnu/libQt5Network.so /usr/lib/aarch64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		camera.cpp \
		light.cpp \
		mainwindow.cpp \
		pfs.cpp \
		gpio.cpp \
		rgb.cpp \
		deal.cpp \
		imagewidget.cpp \
		drawview.cpp \
		rulebar.cpp \
		dialog.cpp \
		sqlsend.cpp \
		sendimg.cpp \
		rulersettings.cpp \
		sendimg_s.cpp \
		gamma_1.cpp \
		guicamera.cpp moc_light.cpp \
		moc_camera.cpp \
		moc_mainwindow.cpp \
		moc_pfs.cpp \
		moc_rgb.cpp \
		moc_deal.cpp \
		moc_drawview.cpp \
		moc_rulebar.cpp \
		moc_dialog.cpp \
		moc_sqlsend.cpp \
		moc_sendimg.cpp \
		moc_rulersettings.cpp \
		moc_sendimg_s.cpp \
		moc_gamma_1.cpp \
		moc_guicamera.cpp
OBJECTS       = main.o \
		camera.o \
		light.o \
		mainwindow.o \
		pfs.o \
		gpio.o \
		rgb.o \
		deal.o \
		imagewidget.o \
		drawview.o \
		rulebar.o \
		dialog.o \
		sqlsend.o \
		sendimg.o \
		rulersettings.o \
		sendimg_s.o \
		gamma_1.o \
		guicamera.o \
		moc_light.o \
		moc_camera.o \
		moc_mainwindow.o \
		moc_pfs.o \
		moc_rgb.o \
		moc_deal.o \
		moc_drawview.o \
		moc_rulebar.o \
		moc_dialog.o \
		moc_sqlsend.o \
		moc_sendimg.o \
		moc_rulersettings.o \
		moc_sendimg_s.o \
		moc_gamma_1.o \
		moc_guicamera.o
DIST          = /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf \
		framework_3.pro light.h \
		BaslerCamera.h \
		BaslerCameraArray.h \
		BaslerCameraCameraEventHandler.h \
		BaslerCameraCameraParams.h \
		BaslerCameraChunkDataParams.h \
		BaslerCameraConfigurationEventHandler.h \
		BaslerCameraEventParams.h \
		BaslerCameraGrabResultData.h \
		BaslerCameraGrabResultPtr.h \
		BaslerCameraImageEventHandler.h \
		BaslerCameraStreamParams.h \
		BaslerCameraTLParams.h \
		camera.h \
		mainwindow.h \
		pfs.h \
		jetsonGPIO.h \
		gpio.h \
		rgb.h \
		deal.h \
		imagewidget.h \
		drawview.h \
		rulebar.h \
		dialog.h \
		sqlsend.h \
		sendimg.h \
		rulersettings.h \
		sendimg_s.h \
		gamma_1.h \
		guicamera.h main.cpp \
		camera.cpp \
		light.cpp \
		mainwindow.cpp \
		pfs.cpp \
		gpio.cpp \
		rgb.cpp \
		deal.cpp \
		imagewidget.cpp \
		drawview.cpp \
		rulebar.cpp \
		dialog.cpp \
		sqlsend.cpp \
		sendimg.cpp \
		rulersettings.cpp \
		sendimg_s.cpp \
		gamma_1.cpp \
		guicamera.cpp
QMAKE_TARGET  = blaser_app
DESTDIR       = 
TARGET        = blaser_app


first: all
####### Build rules

blaser_app: ui_light.h ui_mainwindow.h ui_pfs.h ui_rgb.h ui_deal.h ui_dialog.h ui_rulersettings.h ui_gamma_1.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: framework_3.pro /usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf \
		framework_3.pro
	$(QMAKE) -o Makefile framework_3.pro -spec linux-g++
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf:
framework_3.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile framework_3.pro -spec linux-g++

qmake_all: FORCE


all: Makefile blaser_app

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents light.h BaslerCamera.h BaslerCameraArray.h BaslerCameraCameraEventHandler.h BaslerCameraCameraParams.h BaslerCameraChunkDataParams.h BaslerCameraConfigurationEventHandler.h BaslerCameraEventParams.h BaslerCameraGrabResultData.h BaslerCameraGrabResultPtr.h BaslerCameraImageEventHandler.h BaslerCameraStreamParams.h BaslerCameraTLParams.h camera.h mainwindow.h pfs.h jetsonGPIO.h gpio.h rgb.h deal.h imagewidget.h drawview.h rulebar.h dialog.h sqlsend.h sendimg.h rulersettings.h sendimg_s.h gamma_1.h guicamera.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp camera.cpp light.cpp mainwindow.cpp pfs.cpp gpio.cpp rgb.cpp deal.cpp imagewidget.cpp drawview.cpp rulebar.cpp dialog.cpp sqlsend.cpp sendimg.cpp rulersettings.cpp sendimg_s.cpp gamma_1.cpp guicamera.cpp $(DISTDIR)/
	$(COPY_FILE) --parents light.ui mainwindow.ui pfs.ui rgb.ui deal.ui dialog.ui rulersettings.ui gamma_1.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_light.cpp moc_camera.cpp moc_mainwindow.cpp moc_pfs.cpp moc_rgb.cpp moc_deal.cpp moc_drawview.cpp moc_rulebar.cpp moc_dialog.cpp moc_sqlsend.cpp moc_sendimg.cpp moc_rulersettings.cpp moc_sendimg_s.cpp moc_gamma_1.cpp moc_guicamera.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_light.cpp moc_camera.cpp moc_mainwindow.cpp moc_pfs.cpp moc_rgb.cpp moc_deal.cpp moc_drawview.cpp moc_rulebar.cpp moc_dialog.cpp moc_sqlsend.cpp moc_sendimg.cpp moc_rulersettings.cpp moc_sendimg_s.cpp moc_gamma_1.cpp moc_guicamera.cpp
moc_light.cpp: light.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/cat/software/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cat/software -I/opt/pylon/include -I/usr/include/opencv4/opencv2 -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtSql -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/aarch64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/aarch64-linux-gnu/10/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include light.h -o moc_light.cpp

moc_camera.cpp: camera.h \
		guicamera.h \
		pylon/PylonIncludes.h \
		pylon/Platform.h \
		pylon/PylonLinkage.h \
		GenICamVersion.h \
		_GenICamVersion.h \
		Base/GCLinkage.h \
		Base/GCTypes.h \
		Base/GCNamespace.h \
		Base/GCString.h \
		Base/GCStringVector.h \
		GenApi/GenApi.h \
		Base/GCBase.h \
		Base/GCArray.h \
		Base/GCException.h \
		Base/GCCompatibility.h \
		Base/GCUtilities.h \
		Base/GCRTSSUtilities.h \
		GenApi/GenApiDll.h \
		GenApi/GenApiNamespace.h \
		GenApi/Pointer.h \
		GenICamFwd.h \
		GenApi/IEnumeration.h \
		GenApi/IEnumEntry.h \
		GenApi/IValue.h \
		GenApi/Types.h \
		GenApi/Autovector.h \
		GenApi/IBase.h \
		GenApi/Reference.h \
		GenApi/INode.h \
		GenApi/Container.h \
		GenApi/IFloat.h \
		GenApi/IInteger.h \
		GenApi/ICategory.h \
		GenApi/IRegister.h \
		GenApi/IBoolean.h \
		GenApi/IPort.h \
		GenApi/IPortStacked.h \
		GenApi/IPortRecorder.h \
		GenApi/IPortConstruct.h \
		GenApi/IChunkPort.h \
		GenApi/IString.h \
		GenApi/INodeMap.h \
		GenApi/Synch.h \
		GenApi/ConcatenatedWrite.h \
		GenApi/IDestroy.h \
		GenApi/IDeviceInfo.h \
		GenApi/ISelector.h \
		GenApi/ICommand.h \
		GenApi/IUserData.h \
		GenApi/NodeMapRef.h \
		GenApi/NodeMapFactory.h \
		GenApi/GenApiVersion.h \
		GenApi/NodeCallback.h \
		GenApi/Persistence.h \
		GenApi/SelectorSet.h \
		GenApi/ISelectorDigit.h \
		GenApi/SelectorState.h \
		GenApi/StructPort.h \
		GenApi/PortImpl.h \
		GenApi/GenApiLinkage.h \
		pylon/stdinclude.h \
		pylon/TypeMappings.h \
		pylon/PylonBase.h \
		pylon/PylonVersionInfo.h \
		pylon/Info.h \
		pylon/TlInfo.h \
		pylon/DeviceClass.h \
		pylon/DeviceInfo.h \
		pylon/Container.h \
		pylon/InterfaceInfo.h \
		pylon/StaticDefectPixel.h \
		pylon/DeviceFactory.h \
		pylon/DeviceAccessMode.h \
		pylon/PylonVersionNumber.h \
		pylon/TransportLayer.h \
		pylon/Interface.h \
		pylon/TlFactory.h \
		pylon/EventAdapter.h \
		pylon/Callback.h \
		pylon/Device.h \
		pylon/WaitObject.h \
		pylon/WaitObjects.h \
		pylon/StreamGrabber.h \
		pylon/PixelType.h \
		pylon/Pixel.h \
		pylon/PixelTypeMapper.h \
		GenApi/IEnumerationT.h \
		GenApi/Compatibility.h \
		pylon/Result.h \
		pylon/PayloadType.h \
		pylon/ResultImage.h \
		pylon/Image.h \
		pylon/SharedByteBuffer.h \
		pylon/PylonDataComponent.h \
		pylon/PylonDataContainer.h \
		pylon/ChunkParser.h \
		pylon/EventGrabber.h \
		pylon/EventGrabberProxy.h \
		pylon/NodeMapProxy.h \
		pylon/AcquireSingleFrameConfiguration.h \
		pylon/InstantCamera.h \
		pylon/ImageEventHandler.h \
		pylon/GrabResultPtr.h \
		pylon/GrabResultData.h \
		pylon/ConfigurationEventHandler.h \
		pylon/CameraEventHandler.h \
		pylon/BufferFactory.h \
		pylon/SfncVersion.h \
		pylon/ECleanup.h \
		pylon/ERegistrationMode.h \
		pylon/ETimeoutHandling.h \
		pylon/_InstantCameraParams.h \
		pylon/ParameterIncludes.h \
		pylon/ArrayParameter.h \
		pylon/Parameter.h \
		pylon/BooleanParameter.h \
		pylon/CommandParameter.h \
		pylon/EnumParameter.h \
		pylon/FloatParameter.h \
		pylon/IntegerParameter.h \
		pylon/StringParameter.h \
		pylon/EnumParameterT.h \
		pylon/ConfigurationHelper.h \
		pylon/InstantCameraArray.h \
		pylon/AcquireContinuousConfiguration.h \
		pylon/SoftwareTriggerConfiguration.h \
		pylon/InstantInterface.h \
		pylon/_BaslerUniversalInterfaceParams.h \
		pylon/PylonUtilityIncludes.h \
		pylon/PylonUtility.h \
		pylon/PylonImage.h \
		pylon/PylonImageBase.h \
		pylon/ReusableImage.h \
		pylon/ImagePersistence.h \
		pylon/PixelData.h \
		pylon/PylonImageUserBufferEventHandler.h \
		pylon/ImageDecompressor.h \
		pylon/ImageFormatConverter.h \
		pylon/_ImageFormatConverterParams.h \
		pylon/FeaturePersistence.h \
		pylon/VideoWriter.h \
		pylon/_VideoWriterParams.h \
		pylon/BaslerUniversalInstantCamera.h \
		pylon/_BaslerUniversalCameraParams.h \
		pylon/_BaslerUniversalStreamParams.h \
		pylon/_BaslerUniversalEventParams.h \
		pylon/_BaslerUniversalTLParams.h \
		pylon/BaslerUniversalConfigurationEventHandler.h \
		pylon/BaslerUniversalImageEventHandler.h \
		pylon/BaslerUniversalGrabResultPtr.h \
		pylon/BaslerUniversalGrabResultData.h \
		pylon/_BaslerUniversalChunkDataParams.h \
		pylon/private/DeviceSpecificGrabResultPtr.h \
		pylon/BaslerUniversalCameraEventHandler.h \
		pylon/private/DeviceSpecificInstantCamera.h \
		pylon/private/DeviceSpecificConfigurationEventHandlerTie.h \
		pylon/private/DeviceSpecificImageEventHandlerTie.h \
		pylon/private/DeviceSpecificCameraEventHandlerTie.h \
		pylon/gige/PylonGigEDevice.h \
		pylon/gige/PylonGigE.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/cat/software/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cat/software -I/opt/pylon/include -I/usr/include/opencv4/opencv2 -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtSql -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/aarch64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/aarch64-linux-gnu/10/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include camera.h -o moc_camera.cpp

moc_mainwindow.cpp: mainwindow.h \
		jetsonGPIO.h \
		guicamera.h \
		pylon/PylonIncludes.h \
		pylon/Platform.h \
		pylon/PylonLinkage.h \
		GenICamVersion.h \
		_GenICamVersion.h \
		Base/GCLinkage.h \
		Base/GCTypes.h \
		Base/GCNamespace.h \
		Base/GCString.h \
		Base/GCStringVector.h \
		GenApi/GenApi.h \
		Base/GCBase.h \
		Base/GCArray.h \
		Base/GCException.h \
		Base/GCCompatibility.h \
		Base/GCUtilities.h \
		Base/GCRTSSUtilities.h \
		GenApi/GenApiDll.h \
		GenApi/GenApiNamespace.h \
		GenApi/Pointer.h \
		GenICamFwd.h \
		GenApi/IEnumeration.h \
		GenApi/IEnumEntry.h \
		GenApi/IValue.h \
		GenApi/Types.h \
		GenApi/Autovector.h \
		GenApi/IBase.h \
		GenApi/Reference.h \
		GenApi/INode.h \
		GenApi/Container.h \
		GenApi/IFloat.h \
		GenApi/IInteger.h \
		GenApi/ICategory.h \
		GenApi/IRegister.h \
		GenApi/IBoolean.h \
		GenApi/IPort.h \
		GenApi/IPortStacked.h \
		GenApi/IPortRecorder.h \
		GenApi/IPortConstruct.h \
		GenApi/IChunkPort.h \
		GenApi/IString.h \
		GenApi/INodeMap.h \
		GenApi/Synch.h \
		GenApi/ConcatenatedWrite.h \
		GenApi/IDestroy.h \
		GenApi/IDeviceInfo.h \
		GenApi/ISelector.h \
		GenApi/ICommand.h \
		GenApi/IUserData.h \
		GenApi/NodeMapRef.h \
		GenApi/NodeMapFactory.h \
		GenApi/GenApiVersion.h \
		GenApi/NodeCallback.h \
		GenApi/Persistence.h \
		GenApi/SelectorSet.h \
		GenApi/ISelectorDigit.h \
		GenApi/SelectorState.h \
		GenApi/StructPort.h \
		GenApi/PortImpl.h \
		GenApi/GenApiLinkage.h \
		pylon/stdinclude.h \
		pylon/TypeMappings.h \
		pylon/PylonBase.h \
		pylon/PylonVersionInfo.h \
		pylon/Info.h \
		pylon/TlInfo.h \
		pylon/DeviceClass.h \
		pylon/DeviceInfo.h \
		pylon/Container.h \
		pylon/InterfaceInfo.h \
		pylon/StaticDefectPixel.h \
		pylon/DeviceFactory.h \
		pylon/DeviceAccessMode.h \
		pylon/PylonVersionNumber.h \
		pylon/TransportLayer.h \
		pylon/Interface.h \
		pylon/TlFactory.h \
		pylon/EventAdapter.h \
		pylon/Callback.h \
		pylon/Device.h \
		pylon/WaitObject.h \
		pylon/WaitObjects.h \
		pylon/StreamGrabber.h \
		pylon/PixelType.h \
		pylon/Pixel.h \
		pylon/PixelTypeMapper.h \
		GenApi/IEnumerationT.h \
		GenApi/Compatibility.h \
		pylon/Result.h \
		pylon/PayloadType.h \
		pylon/ResultImage.h \
		pylon/Image.h \
		pylon/SharedByteBuffer.h \
		pylon/PylonDataComponent.h \
		pylon/PylonDataContainer.h \
		pylon/ChunkParser.h \
		pylon/EventGrabber.h \
		pylon/EventGrabberProxy.h \
		pylon/NodeMapProxy.h \
		pylon/AcquireSingleFrameConfiguration.h \
		pylon/InstantCamera.h \
		pylon/ImageEventHandler.h \
		pylon/GrabResultPtr.h \
		pylon/GrabResultData.h \
		pylon/ConfigurationEventHandler.h \
		pylon/CameraEventHandler.h \
		pylon/BufferFactory.h \
		pylon/SfncVersion.h \
		pylon/ECleanup.h \
		pylon/ERegistrationMode.h \
		pylon/ETimeoutHandling.h \
		pylon/_InstantCameraParams.h \
		pylon/ParameterIncludes.h \
		pylon/ArrayParameter.h \
		pylon/Parameter.h \
		pylon/BooleanParameter.h \
		pylon/CommandParameter.h \
		pylon/EnumParameter.h \
		pylon/FloatParameter.h \
		pylon/IntegerParameter.h \
		pylon/StringParameter.h \
		pylon/EnumParameterT.h \
		pylon/ConfigurationHelper.h \
		pylon/InstantCameraArray.h \
		pylon/AcquireContinuousConfiguration.h \
		pylon/SoftwareTriggerConfiguration.h \
		pylon/InstantInterface.h \
		pylon/_BaslerUniversalInterfaceParams.h \
		pylon/PylonUtilityIncludes.h \
		pylon/PylonUtility.h \
		pylon/PylonImage.h \
		pylon/PylonImageBase.h \
		pylon/ReusableImage.h \
		pylon/ImagePersistence.h \
		pylon/PixelData.h \
		pylon/PylonImageUserBufferEventHandler.h \
		pylon/ImageDecompressor.h \
		pylon/ImageFormatConverter.h \
		pylon/_ImageFormatConverterParams.h \
		pylon/FeaturePersistence.h \
		pylon/VideoWriter.h \
		pylon/_VideoWriterParams.h \
		pylon/BaslerUniversalInstantCamera.h \
		pylon/_BaslerUniversalCameraParams.h \
		pylon/_BaslerUniversalStreamParams.h \
		pylon/_BaslerUniversalEventParams.h \
		pylon/_BaslerUniversalTLParams.h \
		pylon/BaslerUniversalConfigurationEventHandler.h \
		pylon/BaslerUniversalImageEventHandler.h \
		pylon/BaslerUniversalGrabResultPtr.h \
		pylon/BaslerUniversalGrabResultData.h \
		pylon/_BaslerUniversalChunkDataParams.h \
		pylon/private/DeviceSpecificGrabResultPtr.h \
		pylon/BaslerUniversalCameraEventHandler.h \
		pylon/private/DeviceSpecificInstantCamera.h \
		pylon/private/DeviceSpecificConfigurationEventHandlerTie.h \
		pylon/private/DeviceSpecificImageEventHandlerTie.h \
		pylon/private/DeviceSpecificCameraEventHandlerTie.h \
		pylon/gige/PylonGigEDevice.h \
		pylon/gige/PylonGigE.h \
		camera.h \
		dialog.h \
		sqlsend.h \
		sendimg.h \
		rulersettings.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/cat/software/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cat/software -I/opt/pylon/include -I/usr/include/opencv4/opencv2 -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtSql -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/aarch64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/aarch64-linux-gnu/10/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_pfs.cpp: pfs.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/cat/software/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cat/software -I/opt/pylon/include -I/usr/include/opencv4/opencv2 -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtSql -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/aarch64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/aarch64-linux-gnu/10/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include pfs.h -o moc_pfs.cpp

moc_rgb.cpp: rgb.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/cat/software/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cat/software -I/opt/pylon/include -I/usr/include/opencv4/opencv2 -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtSql -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/aarch64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/aarch64-linux-gnu/10/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include rgb.h -o moc_rgb.cpp

moc_deal.cpp: deal.h \
		imagewidget.h \
		rulersettings.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/cat/software/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cat/software -I/opt/pylon/include -I/usr/include/opencv4/opencv2 -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtSql -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/aarch64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/aarch64-linux-gnu/10/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include deal.h -o moc_deal.cpp

moc_drawview.cpp: drawview.h \
		rulebar.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/cat/software/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cat/software -I/opt/pylon/include -I/usr/include/opencv4/opencv2 -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtSql -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/aarch64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/aarch64-linux-gnu/10/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include drawview.h -o moc_drawview.cpp

moc_rulebar.cpp: rulebar.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/cat/software/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cat/software -I/opt/pylon/include -I/usr/include/opencv4/opencv2 -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtSql -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/aarch64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/aarch64-linux-gnu/10/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include rulebar.h -o moc_rulebar.cpp

moc_dialog.cpp: dialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/cat/software/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cat/software -I/opt/pylon/include -I/usr/include/opencv4/opencv2 -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtSql -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/aarch64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/aarch64-linux-gnu/10/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include dialog.h -o moc_dialog.cpp

moc_sqlsend.cpp: sqlsend.h \
		sendimg.h \
		guicamera.h \
		pylon/PylonIncludes.h \
		pylon/Platform.h \
		pylon/PylonLinkage.h \
		GenICamVersion.h \
		_GenICamVersion.h \
		Base/GCLinkage.h \
		Base/GCTypes.h \
		Base/GCNamespace.h \
		Base/GCString.h \
		Base/GCStringVector.h \
		GenApi/GenApi.h \
		Base/GCBase.h \
		Base/GCArray.h \
		Base/GCException.h \
		Base/GCCompatibility.h \
		Base/GCUtilities.h \
		Base/GCRTSSUtilities.h \
		GenApi/GenApiDll.h \
		GenApi/GenApiNamespace.h \
		GenApi/Pointer.h \
		GenICamFwd.h \
		GenApi/IEnumeration.h \
		GenApi/IEnumEntry.h \
		GenApi/IValue.h \
		GenApi/Types.h \
		GenApi/Autovector.h \
		GenApi/IBase.h \
		GenApi/Reference.h \
		GenApi/INode.h \
		GenApi/Container.h \
		GenApi/IFloat.h \
		GenApi/IInteger.h \
		GenApi/ICategory.h \
		GenApi/IRegister.h \
		GenApi/IBoolean.h \
		GenApi/IPort.h \
		GenApi/IPortStacked.h \
		GenApi/IPortRecorder.h \
		GenApi/IPortConstruct.h \
		GenApi/IChunkPort.h \
		GenApi/IString.h \
		GenApi/INodeMap.h \
		GenApi/Synch.h \
		GenApi/ConcatenatedWrite.h \
		GenApi/IDestroy.h \
		GenApi/IDeviceInfo.h \
		GenApi/ISelector.h \
		GenApi/ICommand.h \
		GenApi/IUserData.h \
		GenApi/NodeMapRef.h \
		GenApi/NodeMapFactory.h \
		GenApi/GenApiVersion.h \
		GenApi/NodeCallback.h \
		GenApi/Persistence.h \
		GenApi/SelectorSet.h \
		GenApi/ISelectorDigit.h \
		GenApi/SelectorState.h \
		GenApi/StructPort.h \
		GenApi/PortImpl.h \
		GenApi/GenApiLinkage.h \
		pylon/stdinclude.h \
		pylon/TypeMappings.h \
		pylon/PylonBase.h \
		pylon/PylonVersionInfo.h \
		pylon/Info.h \
		pylon/TlInfo.h \
		pylon/DeviceClass.h \
		pylon/DeviceInfo.h \
		pylon/Container.h \
		pylon/InterfaceInfo.h \
		pylon/StaticDefectPixel.h \
		pylon/DeviceFactory.h \
		pylon/DeviceAccessMode.h \
		pylon/PylonVersionNumber.h \
		pylon/TransportLayer.h \
		pylon/Interface.h \
		pylon/TlFactory.h \
		pylon/EventAdapter.h \
		pylon/Callback.h \
		pylon/Device.h \
		pylon/WaitObject.h \
		pylon/WaitObjects.h \
		pylon/StreamGrabber.h \
		pylon/PixelType.h \
		pylon/Pixel.h \
		pylon/PixelTypeMapper.h \
		GenApi/IEnumerationT.h \
		GenApi/Compatibility.h \
		pylon/Result.h \
		pylon/PayloadType.h \
		pylon/ResultImage.h \
		pylon/Image.h \
		pylon/SharedByteBuffer.h \
		pylon/PylonDataComponent.h \
		pylon/PylonDataContainer.h \
		pylon/ChunkParser.h \
		pylon/EventGrabber.h \
		pylon/EventGrabberProxy.h \
		pylon/NodeMapProxy.h \
		pylon/AcquireSingleFrameConfiguration.h \
		pylon/InstantCamera.h \
		pylon/ImageEventHandler.h \
		pylon/GrabResultPtr.h \
		pylon/GrabResultData.h \
		pylon/ConfigurationEventHandler.h \
		pylon/CameraEventHandler.h \
		pylon/BufferFactory.h \
		pylon/SfncVersion.h \
		pylon/ECleanup.h \
		pylon/ERegistrationMode.h \
		pylon/ETimeoutHandling.h \
		pylon/_InstantCameraParams.h \
		pylon/ParameterIncludes.h \
		pylon/ArrayParameter.h \
		pylon/Parameter.h \
		pylon/BooleanParameter.h \
		pylon/CommandParameter.h \
		pylon/EnumParameter.h \
		pylon/FloatParameter.h \
		pylon/IntegerParameter.h \
		pylon/StringParameter.h \
		pylon/EnumParameterT.h \
		pylon/ConfigurationHelper.h \
		pylon/InstantCameraArray.h \
		pylon/AcquireContinuousConfiguration.h \
		pylon/SoftwareTriggerConfiguration.h \
		pylon/InstantInterface.h \
		pylon/_BaslerUniversalInterfaceParams.h \
		pylon/PylonUtilityIncludes.h \
		pylon/PylonUtility.h \
		pylon/PylonImage.h \
		pylon/PylonImageBase.h \
		pylon/ReusableImage.h \
		pylon/ImagePersistence.h \
		pylon/PixelData.h \
		pylon/PylonImageUserBufferEventHandler.h \
		pylon/ImageDecompressor.h \
		pylon/ImageFormatConverter.h \
		pylon/_ImageFormatConverterParams.h \
		pylon/FeaturePersistence.h \
		pylon/VideoWriter.h \
		pylon/_VideoWriterParams.h \
		pylon/BaslerUniversalInstantCamera.h \
		pylon/_BaslerUniversalCameraParams.h \
		pylon/_BaslerUniversalStreamParams.h \
		pylon/_BaslerUniversalEventParams.h \
		pylon/_BaslerUniversalTLParams.h \
		pylon/BaslerUniversalConfigurationEventHandler.h \
		pylon/BaslerUniversalImageEventHandler.h \
		pylon/BaslerUniversalGrabResultPtr.h \
		pylon/BaslerUniversalGrabResultData.h \
		pylon/_BaslerUniversalChunkDataParams.h \
		pylon/private/DeviceSpecificGrabResultPtr.h \
		pylon/BaslerUniversalCameraEventHandler.h \
		pylon/private/DeviceSpecificInstantCamera.h \
		pylon/private/DeviceSpecificConfigurationEventHandlerTie.h \
		pylon/private/DeviceSpecificImageEventHandlerTie.h \
		pylon/private/DeviceSpecificCameraEventHandlerTie.h \
		pylon/gige/PylonGigEDevice.h \
		pylon/gige/PylonGigE.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/cat/software/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cat/software -I/opt/pylon/include -I/usr/include/opencv4/opencv2 -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtSql -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/aarch64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/aarch64-linux-gnu/10/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include sqlsend.h -o moc_sqlsend.cpp

moc_sendimg.cpp: sendimg.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/cat/software/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cat/software -I/opt/pylon/include -I/usr/include/opencv4/opencv2 -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtSql -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/aarch64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/aarch64-linux-gnu/10/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include sendimg.h -o moc_sendimg.cpp

moc_rulersettings.cpp: rulersettings.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/cat/software/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cat/software -I/opt/pylon/include -I/usr/include/opencv4/opencv2 -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtSql -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/aarch64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/aarch64-linux-gnu/10/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include rulersettings.h -o moc_rulersettings.cpp

moc_sendimg_s.cpp: sendimg_s.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/cat/software/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cat/software -I/opt/pylon/include -I/usr/include/opencv4/opencv2 -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtSql -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/aarch64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/aarch64-linux-gnu/10/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include sendimg_s.h -o moc_sendimg_s.cpp

moc_gamma_1.cpp: gamma_1.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/cat/software/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cat/software -I/opt/pylon/include -I/usr/include/opencv4/opencv2 -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtSql -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/aarch64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/aarch64-linux-gnu/10/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include gamma_1.h -o moc_gamma_1.cpp

moc_guicamera.cpp: guicamera.h \
		pylon/PylonIncludes.h \
		pylon/Platform.h \
		pylon/PylonLinkage.h \
		GenICamVersion.h \
		_GenICamVersion.h \
		Base/GCLinkage.h \
		Base/GCTypes.h \
		Base/GCNamespace.h \
		Base/GCString.h \
		Base/GCStringVector.h \
		GenApi/GenApi.h \
		Base/GCBase.h \
		Base/GCArray.h \
		Base/GCException.h \
		Base/GCCompatibility.h \
		Base/GCUtilities.h \
		Base/GCRTSSUtilities.h \
		GenApi/GenApiDll.h \
		GenApi/GenApiNamespace.h \
		GenApi/Pointer.h \
		GenICamFwd.h \
		GenApi/IEnumeration.h \
		GenApi/IEnumEntry.h \
		GenApi/IValue.h \
		GenApi/Types.h \
		GenApi/Autovector.h \
		GenApi/IBase.h \
		GenApi/Reference.h \
		GenApi/INode.h \
		GenApi/Container.h \
		GenApi/IFloat.h \
		GenApi/IInteger.h \
		GenApi/ICategory.h \
		GenApi/IRegister.h \
		GenApi/IBoolean.h \
		GenApi/IPort.h \
		GenApi/IPortStacked.h \
		GenApi/IPortRecorder.h \
		GenApi/IPortConstruct.h \
		GenApi/IChunkPort.h \
		GenApi/IString.h \
		GenApi/INodeMap.h \
		GenApi/Synch.h \
		GenApi/ConcatenatedWrite.h \
		GenApi/IDestroy.h \
		GenApi/IDeviceInfo.h \
		GenApi/ISelector.h \
		GenApi/ICommand.h \
		GenApi/IUserData.h \
		GenApi/NodeMapRef.h \
		GenApi/NodeMapFactory.h \
		GenApi/GenApiVersion.h \
		GenApi/NodeCallback.h \
		GenApi/Persistence.h \
		GenApi/SelectorSet.h \
		GenApi/ISelectorDigit.h \
		GenApi/SelectorState.h \
		GenApi/StructPort.h \
		GenApi/PortImpl.h \
		GenApi/GenApiLinkage.h \
		pylon/stdinclude.h \
		pylon/TypeMappings.h \
		pylon/PylonBase.h \
		pylon/PylonVersionInfo.h \
		pylon/Info.h \
		pylon/TlInfo.h \
		pylon/DeviceClass.h \
		pylon/DeviceInfo.h \
		pylon/Container.h \
		pylon/InterfaceInfo.h \
		pylon/StaticDefectPixel.h \
		pylon/DeviceFactory.h \
		pylon/DeviceAccessMode.h \
		pylon/PylonVersionNumber.h \
		pylon/TransportLayer.h \
		pylon/Interface.h \
		pylon/TlFactory.h \
		pylon/EventAdapter.h \
		pylon/Callback.h \
		pylon/Device.h \
		pylon/WaitObject.h \
		pylon/WaitObjects.h \
		pylon/StreamGrabber.h \
		pylon/PixelType.h \
		pylon/Pixel.h \
		pylon/PixelTypeMapper.h \
		GenApi/IEnumerationT.h \
		GenApi/Compatibility.h \
		pylon/Result.h \
		pylon/PayloadType.h \
		pylon/ResultImage.h \
		pylon/Image.h \
		pylon/SharedByteBuffer.h \
		pylon/PylonDataComponent.h \
		pylon/PylonDataContainer.h \
		pylon/ChunkParser.h \
		pylon/EventGrabber.h \
		pylon/EventGrabberProxy.h \
		pylon/NodeMapProxy.h \
		pylon/AcquireSingleFrameConfiguration.h \
		pylon/InstantCamera.h \
		pylon/ImageEventHandler.h \
		pylon/GrabResultPtr.h \
		pylon/GrabResultData.h \
		pylon/ConfigurationEventHandler.h \
		pylon/CameraEventHandler.h \
		pylon/BufferFactory.h \
		pylon/SfncVersion.h \
		pylon/ECleanup.h \
		pylon/ERegistrationMode.h \
		pylon/ETimeoutHandling.h \
		pylon/_InstantCameraParams.h \
		pylon/ParameterIncludes.h \
		pylon/ArrayParameter.h \
		pylon/Parameter.h \
		pylon/BooleanParameter.h \
		pylon/CommandParameter.h \
		pylon/EnumParameter.h \
		pylon/FloatParameter.h \
		pylon/IntegerParameter.h \
		pylon/StringParameter.h \
		pylon/EnumParameterT.h \
		pylon/ConfigurationHelper.h \
		pylon/InstantCameraArray.h \
		pylon/AcquireContinuousConfiguration.h \
		pylon/SoftwareTriggerConfiguration.h \
		pylon/InstantInterface.h \
		pylon/_BaslerUniversalInterfaceParams.h \
		pylon/PylonUtilityIncludes.h \
		pylon/PylonUtility.h \
		pylon/PylonImage.h \
		pylon/PylonImageBase.h \
		pylon/ReusableImage.h \
		pylon/ImagePersistence.h \
		pylon/PixelData.h \
		pylon/PylonImageUserBufferEventHandler.h \
		pylon/ImageDecompressor.h \
		pylon/ImageFormatConverter.h \
		pylon/_ImageFormatConverterParams.h \
		pylon/FeaturePersistence.h \
		pylon/VideoWriter.h \
		pylon/_VideoWriterParams.h \
		pylon/BaslerUniversalInstantCamera.h \
		pylon/_BaslerUniversalCameraParams.h \
		pylon/_BaslerUniversalStreamParams.h \
		pylon/_BaslerUniversalEventParams.h \
		pylon/_BaslerUniversalTLParams.h \
		pylon/BaslerUniversalConfigurationEventHandler.h \
		pylon/BaslerUniversalImageEventHandler.h \
		pylon/BaslerUniversalGrabResultPtr.h \
		pylon/BaslerUniversalGrabResultData.h \
		pylon/_BaslerUniversalChunkDataParams.h \
		pylon/private/DeviceSpecificGrabResultPtr.h \
		pylon/BaslerUniversalCameraEventHandler.h \
		pylon/private/DeviceSpecificInstantCamera.h \
		pylon/private/DeviceSpecificConfigurationEventHandlerTie.h \
		pylon/private/DeviceSpecificImageEventHandlerTie.h \
		pylon/private/DeviceSpecificCameraEventHandlerTie.h \
		pylon/gige/PylonGigEDevice.h \
		pylon/gige/PylonGigE.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/cat/software/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cat/software -I/opt/pylon/include -I/usr/include/opencv4/opencv2 -I/usr/include/opencv4 -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtSql -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/aarch64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/aarch64-linux-gnu/10/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include guicamera.h -o moc_guicamera.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_light.h ui_mainwindow.h ui_pfs.h ui_rgb.h ui_deal.h ui_dialog.h ui_rulersettings.h ui_gamma_1.h
compiler_uic_clean:
	-$(DEL_FILE) ui_light.h ui_mainwindow.h ui_pfs.h ui_rgb.h ui_deal.h ui_dialog.h ui_rulersettings.h ui_gamma_1.h
ui_light.h: light.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic light.ui -o ui_light.h

ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic \
		light.h \
		pfs.h \
		rgb.h \
		gamma_1.h
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_pfs.h: pfs.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic pfs.ui -o ui_pfs.h

ui_rgb.h: rgb.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic rgb.ui -o ui_rgb.h

ui_deal.h: deal.ui \
		/usr/lib/qt5/bin/uic \
		drawview.h \
		rulebar.h
	/usr/lib/qt5/bin/uic deal.ui -o ui_deal.h

ui_dialog.h: dialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dialog.ui -o ui_dialog.h

ui_rulersettings.h: rulersettings.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic rulersettings.ui -o ui_rulersettings.h

ui_gamma_1.h: gamma_1.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gamma_1.ui -o ui_gamma_1.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		jetsonGPIO.h \
		guicamera.h \
		pylon/PylonIncludes.h \
		pylon/Platform.h \
		pylon/PylonLinkage.h \
		GenICamVersion.h \
		_GenICamVersion.h \
		Base/GCLinkage.h \
		Base/GCTypes.h \
		Base/GCNamespace.h \
		Base/GCString.h \
		Base/GCStringVector.h \
		GenApi/GenApi.h \
		Base/GCBase.h \
		Base/GCArray.h \
		Base/GCException.h \
		Base/GCCompatibility.h \
		Base/GCUtilities.h \
		Base/GCRTSSUtilities.h \
		GenApi/GenApiDll.h \
		GenApi/GenApiNamespace.h \
		GenApi/Pointer.h \
		GenICamFwd.h \
		GenApi/IEnumeration.h \
		GenApi/IEnumEntry.h \
		GenApi/IValue.h \
		GenApi/Types.h \
		GenApi/Autovector.h \
		GenApi/IBase.h \
		GenApi/Reference.h \
		GenApi/INode.h \
		GenApi/Container.h \
		GenApi/IFloat.h \
		GenApi/IInteger.h \
		GenApi/ICategory.h \
		GenApi/IRegister.h \
		GenApi/IBoolean.h \
		GenApi/IPort.h \
		GenApi/IPortStacked.h \
		GenApi/IPortRecorder.h \
		GenApi/IPortConstruct.h \
		GenApi/IChunkPort.h \
		GenApi/IString.h \
		GenApi/INodeMap.h \
		GenApi/Synch.h \
		GenApi/ConcatenatedWrite.h \
		GenApi/IDestroy.h \
		GenApi/IDeviceInfo.h \
		GenApi/ISelector.h \
		GenApi/ICommand.h \
		GenApi/IUserData.h \
		GenApi/NodeMapRef.h \
		GenApi/NodeMapFactory.h \
		GenApi/GenApiVersion.h \
		GenApi/NodeCallback.h \
		GenApi/Persistence.h \
		GenApi/SelectorSet.h \
		GenApi/ISelectorDigit.h \
		GenApi/SelectorState.h \
		GenApi/StructPort.h \
		GenApi/PortImpl.h \
		GenApi/GenApiLinkage.h \
		pylon/stdinclude.h \
		pylon/TypeMappings.h \
		pylon/PylonBase.h \
		pylon/PylonVersionInfo.h \
		pylon/Info.h \
		pylon/TlInfo.h \
		pylon/DeviceClass.h \
		pylon/DeviceInfo.h \
		pylon/Container.h \
		pylon/InterfaceInfo.h \
		pylon/StaticDefectPixel.h \
		pylon/DeviceFactory.h \
		pylon/DeviceAccessMode.h \
		pylon/PylonVersionNumber.h \
		pylon/TransportLayer.h \
		pylon/Interface.h \
		pylon/TlFactory.h \
		pylon/EventAdapter.h \
		pylon/Callback.h \
		pylon/Device.h \
		pylon/WaitObject.h \
		pylon/WaitObjects.h \
		pylon/StreamGrabber.h \
		pylon/PixelType.h \
		pylon/Pixel.h \
		pylon/PixelTypeMapper.h \
		GenApi/IEnumerationT.h \
		GenApi/Compatibility.h \
		pylon/Result.h \
		pylon/PayloadType.h \
		pylon/ResultImage.h \
		pylon/Image.h \
		pylon/SharedByteBuffer.h \
		pylon/PylonDataComponent.h \
		pylon/PylonDataContainer.h \
		pylon/ChunkParser.h \
		pylon/EventGrabber.h \
		pylon/EventGrabberProxy.h \
		pylon/NodeMapProxy.h \
		pylon/AcquireSingleFrameConfiguration.h \
		pylon/InstantCamera.h \
		pylon/ImageEventHandler.h \
		pylon/GrabResultPtr.h \
		pylon/GrabResultData.h \
		pylon/ConfigurationEventHandler.h \
		pylon/CameraEventHandler.h \
		pylon/BufferFactory.h \
		pylon/SfncVersion.h \
		pylon/ECleanup.h \
		pylon/ERegistrationMode.h \
		pylon/ETimeoutHandling.h \
		pylon/_InstantCameraParams.h \
		pylon/ParameterIncludes.h \
		pylon/ArrayParameter.h \
		pylon/Parameter.h \
		pylon/BooleanParameter.h \
		pylon/CommandParameter.h \
		pylon/EnumParameter.h \
		pylon/FloatParameter.h \
		pylon/IntegerParameter.h \
		pylon/StringParameter.h \
		pylon/EnumParameterT.h \
		pylon/ConfigurationHelper.h \
		pylon/InstantCameraArray.h \
		pylon/AcquireContinuousConfiguration.h \
		pylon/SoftwareTriggerConfiguration.h \
		pylon/InstantInterface.h \
		pylon/_BaslerUniversalInterfaceParams.h \
		pylon/PylonUtilityIncludes.h \
		pylon/PylonUtility.h \
		pylon/PylonImage.h \
		pylon/PylonImageBase.h \
		pylon/ReusableImage.h \
		pylon/ImagePersistence.h \
		pylon/PixelData.h \
		pylon/PylonImageUserBufferEventHandler.h \
		pylon/ImageDecompressor.h \
		pylon/ImageFormatConverter.h \
		pylon/_ImageFormatConverterParams.h \
		pylon/FeaturePersistence.h \
		pylon/VideoWriter.h \
		pylon/_VideoWriterParams.h \
		pylon/BaslerUniversalInstantCamera.h \
		pylon/_BaslerUniversalCameraParams.h \
		pylon/_BaslerUniversalStreamParams.h \
		pylon/_BaslerUniversalEventParams.h \
		pylon/_BaslerUniversalTLParams.h \
		pylon/BaslerUniversalConfigurationEventHandler.h \
		pylon/BaslerUniversalImageEventHandler.h \
		pylon/BaslerUniversalGrabResultPtr.h \
		pylon/BaslerUniversalGrabResultData.h \
		pylon/_BaslerUniversalChunkDataParams.h \
		pylon/private/DeviceSpecificGrabResultPtr.h \
		pylon/BaslerUniversalCameraEventHandler.h \
		pylon/private/DeviceSpecificInstantCamera.h \
		pylon/private/DeviceSpecificConfigurationEventHandlerTie.h \
		pylon/private/DeviceSpecificImageEventHandlerTie.h \
		pylon/private/DeviceSpecificCameraEventHandlerTie.h \
		pylon/gige/PylonGigEDevice.h \
		pylon/gige/PylonGigE.h \
		camera.h \
		dialog.h \
		sqlsend.h \
		sendimg.h \
		rulersettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

camera.o: camera.cpp camera.h \
		guicamera.h \
		pylon/PylonIncludes.h \
		pylon/Platform.h \
		pylon/PylonLinkage.h \
		GenICamVersion.h \
		_GenICamVersion.h \
		Base/GCLinkage.h \
		Base/GCTypes.h \
		Base/GCNamespace.h \
		Base/GCString.h \
		Base/GCStringVector.h \
		GenApi/GenApi.h \
		Base/GCBase.h \
		Base/GCArray.h \
		Base/GCException.h \
		Base/GCCompatibility.h \
		Base/GCUtilities.h \
		Base/GCRTSSUtilities.h \
		GenApi/GenApiDll.h \
		GenApi/GenApiNamespace.h \
		GenApi/Pointer.h \
		GenICamFwd.h \
		GenApi/IEnumeration.h \
		GenApi/IEnumEntry.h \
		GenApi/IValue.h \
		GenApi/Types.h \
		GenApi/Autovector.h \
		GenApi/IBase.h \
		GenApi/Reference.h \
		GenApi/INode.h \
		GenApi/Container.h \
		GenApi/IFloat.h \
		GenApi/IInteger.h \
		GenApi/ICategory.h \
		GenApi/IRegister.h \
		GenApi/IBoolean.h \
		GenApi/IPort.h \
		GenApi/IPortStacked.h \
		GenApi/IPortRecorder.h \
		GenApi/IPortConstruct.h \
		GenApi/IChunkPort.h \
		GenApi/IString.h \
		GenApi/INodeMap.h \
		GenApi/Synch.h \
		GenApi/ConcatenatedWrite.h \
		GenApi/IDestroy.h \
		GenApi/IDeviceInfo.h \
		GenApi/ISelector.h \
		GenApi/ICommand.h \
		GenApi/IUserData.h \
		GenApi/NodeMapRef.h \
		GenApi/NodeMapFactory.h \
		GenApi/GenApiVersion.h \
		GenApi/NodeCallback.h \
		GenApi/Persistence.h \
		GenApi/SelectorSet.h \
		GenApi/ISelectorDigit.h \
		GenApi/SelectorState.h \
		GenApi/StructPort.h \
		GenApi/PortImpl.h \
		GenApi/GenApiLinkage.h \
		pylon/stdinclude.h \
		pylon/TypeMappings.h \
		pylon/PylonBase.h \
		pylon/PylonVersionInfo.h \
		pylon/Info.h \
		pylon/TlInfo.h \
		pylon/DeviceClass.h \
		pylon/DeviceInfo.h \
		pylon/Container.h \
		pylon/InterfaceInfo.h \
		pylon/StaticDefectPixel.h \
		pylon/DeviceFactory.h \
		pylon/DeviceAccessMode.h \
		pylon/PylonVersionNumber.h \
		pylon/TransportLayer.h \
		pylon/Interface.h \
		pylon/TlFactory.h \
		pylon/EventAdapter.h \
		pylon/Callback.h \
		pylon/Device.h \
		pylon/WaitObject.h \
		pylon/WaitObjects.h \
		pylon/StreamGrabber.h \
		pylon/PixelType.h \
		pylon/Pixel.h \
		pylon/PixelTypeMapper.h \
		GenApi/IEnumerationT.h \
		GenApi/Compatibility.h \
		pylon/Result.h \
		pylon/PayloadType.h \
		pylon/ResultImage.h \
		pylon/Image.h \
		pylon/SharedByteBuffer.h \
		pylon/PylonDataComponent.h \
		pylon/PylonDataContainer.h \
		pylon/ChunkParser.h \
		pylon/EventGrabber.h \
		pylon/EventGrabberProxy.h \
		pylon/NodeMapProxy.h \
		pylon/AcquireSingleFrameConfiguration.h \
		pylon/InstantCamera.h \
		pylon/ImageEventHandler.h \
		pylon/GrabResultPtr.h \
		pylon/GrabResultData.h \
		pylon/ConfigurationEventHandler.h \
		pylon/CameraEventHandler.h \
		pylon/BufferFactory.h \
		pylon/SfncVersion.h \
		pylon/ECleanup.h \
		pylon/ERegistrationMode.h \
		pylon/ETimeoutHandling.h \
		pylon/_InstantCameraParams.h \
		pylon/ParameterIncludes.h \
		pylon/ArrayParameter.h \
		pylon/Parameter.h \
		pylon/BooleanParameter.h \
		pylon/CommandParameter.h \
		pylon/EnumParameter.h \
		pylon/FloatParameter.h \
		pylon/IntegerParameter.h \
		pylon/StringParameter.h \
		pylon/EnumParameterT.h \
		pylon/ConfigurationHelper.h \
		pylon/InstantCameraArray.h \
		pylon/AcquireContinuousConfiguration.h \
		pylon/SoftwareTriggerConfiguration.h \
		pylon/InstantInterface.h \
		pylon/_BaslerUniversalInterfaceParams.h \
		pylon/PylonUtilityIncludes.h \
		pylon/PylonUtility.h \
		pylon/PylonImage.h \
		pylon/PylonImageBase.h \
		pylon/ReusableImage.h \
		pylon/ImagePersistence.h \
		pylon/PixelData.h \
		pylon/PylonImageUserBufferEventHandler.h \
		pylon/ImageDecompressor.h \
		pylon/ImageFormatConverter.h \
		pylon/_ImageFormatConverterParams.h \
		pylon/FeaturePersistence.h \
		pylon/VideoWriter.h \
		pylon/_VideoWriterParams.h \
		pylon/BaslerUniversalInstantCamera.h \
		pylon/_BaslerUniversalCameraParams.h \
		pylon/_BaslerUniversalStreamParams.h \
		pylon/_BaslerUniversalEventParams.h \
		pylon/_BaslerUniversalTLParams.h \
		pylon/BaslerUniversalConfigurationEventHandler.h \
		pylon/BaslerUniversalImageEventHandler.h \
		pylon/BaslerUniversalGrabResultPtr.h \
		pylon/BaslerUniversalGrabResultData.h \
		pylon/_BaslerUniversalChunkDataParams.h \
		pylon/private/DeviceSpecificGrabResultPtr.h \
		pylon/BaslerUniversalCameraEventHandler.h \
		pylon/private/DeviceSpecificInstantCamera.h \
		pylon/private/DeviceSpecificConfigurationEventHandlerTie.h \
		pylon/private/DeviceSpecificImageEventHandlerTie.h \
		pylon/private/DeviceSpecificCameraEventHandlerTie.h \
		pylon/gige/PylonGigEDevice.h \
		pylon/gige/PylonGigE.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

light.o: light.cpp light.h \
		ui_light.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o light.o light.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		jetsonGPIO.h \
		guicamera.h \
		pylon/PylonIncludes.h \
		pylon/Platform.h \
		pylon/PylonLinkage.h \
		GenICamVersion.h \
		_GenICamVersion.h \
		Base/GCLinkage.h \
		Base/GCTypes.h \
		Base/GCNamespace.h \
		Base/GCString.h \
		Base/GCStringVector.h \
		GenApi/GenApi.h \
		Base/GCBase.h \
		Base/GCArray.h \
		Base/GCException.h \
		Base/GCCompatibility.h \
		Base/GCUtilities.h \
		Base/GCRTSSUtilities.h \
		GenApi/GenApiDll.h \
		GenApi/GenApiNamespace.h \
		GenApi/Pointer.h \
		GenICamFwd.h \
		GenApi/IEnumeration.h \
		GenApi/IEnumEntry.h \
		GenApi/IValue.h \
		GenApi/Types.h \
		GenApi/Autovector.h \
		GenApi/IBase.h \
		GenApi/Reference.h \
		GenApi/INode.h \
		GenApi/Container.h \
		GenApi/IFloat.h \
		GenApi/IInteger.h \
		GenApi/ICategory.h \
		GenApi/IRegister.h \
		GenApi/IBoolean.h \
		GenApi/IPort.h \
		GenApi/IPortStacked.h \
		GenApi/IPortRecorder.h \
		GenApi/IPortConstruct.h \
		GenApi/IChunkPort.h \
		GenApi/IString.h \
		GenApi/INodeMap.h \
		GenApi/Synch.h \
		GenApi/ConcatenatedWrite.h \
		GenApi/IDestroy.h \
		GenApi/IDeviceInfo.h \
		GenApi/ISelector.h \
		GenApi/ICommand.h \
		GenApi/IUserData.h \
		GenApi/NodeMapRef.h \
		GenApi/NodeMapFactory.h \
		GenApi/GenApiVersion.h \
		GenApi/NodeCallback.h \
		GenApi/Persistence.h \
		GenApi/SelectorSet.h \
		GenApi/ISelectorDigit.h \
		GenApi/SelectorState.h \
		GenApi/StructPort.h \
		GenApi/PortImpl.h \
		GenApi/GenApiLinkage.h \
		pylon/stdinclude.h \
		pylon/TypeMappings.h \
		pylon/PylonBase.h \
		pylon/PylonVersionInfo.h \
		pylon/Info.h \
		pylon/TlInfo.h \
		pylon/DeviceClass.h \
		pylon/DeviceInfo.h \
		pylon/Container.h \
		pylon/InterfaceInfo.h \
		pylon/StaticDefectPixel.h \
		pylon/DeviceFactory.h \
		pylon/DeviceAccessMode.h \
		pylon/PylonVersionNumber.h \
		pylon/TransportLayer.h \
		pylon/Interface.h \
		pylon/TlFactory.h \
		pylon/EventAdapter.h \
		pylon/Callback.h \
		pylon/Device.h \
		pylon/WaitObject.h \
		pylon/WaitObjects.h \
		pylon/StreamGrabber.h \
		pylon/PixelType.h \
		pylon/Pixel.h \
		pylon/PixelTypeMapper.h \
		GenApi/IEnumerationT.h \
		GenApi/Compatibility.h \
		pylon/Result.h \
		pylon/PayloadType.h \
		pylon/ResultImage.h \
		pylon/Image.h \
		pylon/SharedByteBuffer.h \
		pylon/PylonDataComponent.h \
		pylon/PylonDataContainer.h \
		pylon/ChunkParser.h \
		pylon/EventGrabber.h \
		pylon/EventGrabberProxy.h \
		pylon/NodeMapProxy.h \
		pylon/AcquireSingleFrameConfiguration.h \
		pylon/InstantCamera.h \
		pylon/ImageEventHandler.h \
		pylon/GrabResultPtr.h \
		pylon/GrabResultData.h \
		pylon/ConfigurationEventHandler.h \
		pylon/CameraEventHandler.h \
		pylon/BufferFactory.h \
		pylon/SfncVersion.h \
		pylon/ECleanup.h \
		pylon/ERegistrationMode.h \
		pylon/ETimeoutHandling.h \
		pylon/_InstantCameraParams.h \
		pylon/ParameterIncludes.h \
		pylon/ArrayParameter.h \
		pylon/Parameter.h \
		pylon/BooleanParameter.h \
		pylon/CommandParameter.h \
		pylon/EnumParameter.h \
		pylon/FloatParameter.h \
		pylon/IntegerParameter.h \
		pylon/StringParameter.h \
		pylon/EnumParameterT.h \
		pylon/ConfigurationHelper.h \
		pylon/InstantCameraArray.h \
		pylon/AcquireContinuousConfiguration.h \
		pylon/SoftwareTriggerConfiguration.h \
		pylon/InstantInterface.h \
		pylon/_BaslerUniversalInterfaceParams.h \
		pylon/PylonUtilityIncludes.h \
		pylon/PylonUtility.h \
		pylon/PylonImage.h \
		pylon/PylonImageBase.h \
		pylon/ReusableImage.h \
		pylon/ImagePersistence.h \
		pylon/PixelData.h \
		pylon/PylonImageUserBufferEventHandler.h \
		pylon/ImageDecompressor.h \
		pylon/ImageFormatConverter.h \
		pylon/_ImageFormatConverterParams.h \
		pylon/FeaturePersistence.h \
		pylon/VideoWriter.h \
		pylon/_VideoWriterParams.h \
		pylon/BaslerUniversalInstantCamera.h \
		pylon/_BaslerUniversalCameraParams.h \
		pylon/_BaslerUniversalStreamParams.h \
		pylon/_BaslerUniversalEventParams.h \
		pylon/_BaslerUniversalTLParams.h \
		pylon/BaslerUniversalConfigurationEventHandler.h \
		pylon/BaslerUniversalImageEventHandler.h \
		pylon/BaslerUniversalGrabResultPtr.h \
		pylon/BaslerUniversalGrabResultData.h \
		pylon/_BaslerUniversalChunkDataParams.h \
		pylon/private/DeviceSpecificGrabResultPtr.h \
		pylon/BaslerUniversalCameraEventHandler.h \
		pylon/private/DeviceSpecificInstantCamera.h \
		pylon/private/DeviceSpecificConfigurationEventHandlerTie.h \
		pylon/private/DeviceSpecificImageEventHandlerTie.h \
		pylon/private/DeviceSpecificCameraEventHandlerTie.h \
		pylon/gige/PylonGigEDevice.h \
		pylon/gige/PylonGigE.h \
		camera.h \
		dialog.h \
		sqlsend.h \
		sendimg.h \
		rulersettings.h \
		ui_mainwindow.h \
		gamma_1.h \
		light.h \
		pfs.h \
		rgb.h \
		deal.h \
		imagewidget.h \
		BaslerCamera.h \
		BaslerCameraCameraParams.h \
		BaslerCameraStreamParams.h \
		BaslerCameraEventParams.h \
		BaslerCameraTLParams.h \
		BaslerCameraConfigurationEventHandler.h \
		BaslerCameraImageEventHandler.h \
		BaslerCameraGrabResultPtr.h \
		BaslerCameraGrabResultData.h \
		BaslerCameraChunkDataParams.h \
		BaslerCameraCameraEventHandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

pfs.o: pfs.cpp pfs.h \
		ui_pfs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pfs.o pfs.cpp

gpio.o: gpio.cpp gpio.h \
		jetsonGPIO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpio.o gpio.cpp

rgb.o: rgb.cpp rgb.h \
		ui_rgb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rgb.o rgb.cpp

deal.o: deal.cpp deal.h \
		imagewidget.h \
		rulersettings.h \
		ui_deal.h \
		drawview.h \
		rulebar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o deal.o deal.cpp

imagewidget.o: imagewidget.cpp imagewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagewidget.o imagewidget.cpp

drawview.o: drawview.cpp drawview.h \
		rulebar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawview.o drawview.cpp

rulebar.o: rulebar.cpp rulebar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rulebar.o rulebar.cpp

dialog.o: dialog.cpp dialog.h \
		ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

sqlsend.o: sqlsend.cpp sqlsend.h \
		sendimg.h \
		guicamera.h \
		pylon/PylonIncludes.h \
		pylon/Platform.h \
		pylon/PylonLinkage.h \
		GenICamVersion.h \
		_GenICamVersion.h \
		Base/GCLinkage.h \
		Base/GCTypes.h \
		Base/GCNamespace.h \
		Base/GCString.h \
		Base/GCStringVector.h \
		GenApi/GenApi.h \
		Base/GCBase.h \
		Base/GCArray.h \
		Base/GCException.h \
		Base/GCCompatibility.h \
		Base/GCUtilities.h \
		Base/GCRTSSUtilities.h \
		GenApi/GenApiDll.h \
		GenApi/GenApiNamespace.h \
		GenApi/Pointer.h \
		GenICamFwd.h \
		GenApi/IEnumeration.h \
		GenApi/IEnumEntry.h \
		GenApi/IValue.h \
		GenApi/Types.h \
		GenApi/Autovector.h \
		GenApi/IBase.h \
		GenApi/Reference.h \
		GenApi/INode.h \
		GenApi/Container.h \
		GenApi/IFloat.h \
		GenApi/IInteger.h \
		GenApi/ICategory.h \
		GenApi/IRegister.h \
		GenApi/IBoolean.h \
		GenApi/IPort.h \
		GenApi/IPortStacked.h \
		GenApi/IPortRecorder.h \
		GenApi/IPortConstruct.h \
		GenApi/IChunkPort.h \
		GenApi/IString.h \
		GenApi/INodeMap.h \
		GenApi/Synch.h \
		GenApi/ConcatenatedWrite.h \
		GenApi/IDestroy.h \
		GenApi/IDeviceInfo.h \
		GenApi/ISelector.h \
		GenApi/ICommand.h \
		GenApi/IUserData.h \
		GenApi/NodeMapRef.h \
		GenApi/NodeMapFactory.h \
		GenApi/GenApiVersion.h \
		GenApi/NodeCallback.h \
		GenApi/Persistence.h \
		GenApi/SelectorSet.h \
		GenApi/ISelectorDigit.h \
		GenApi/SelectorState.h \
		GenApi/StructPort.h \
		GenApi/PortImpl.h \
		GenApi/GenApiLinkage.h \
		pylon/stdinclude.h \
		pylon/TypeMappings.h \
		pylon/PylonBase.h \
		pylon/PylonVersionInfo.h \
		pylon/Info.h \
		pylon/TlInfo.h \
		pylon/DeviceClass.h \
		pylon/DeviceInfo.h \
		pylon/Container.h \
		pylon/InterfaceInfo.h \
		pylon/StaticDefectPixel.h \
		pylon/DeviceFactory.h \
		pylon/DeviceAccessMode.h \
		pylon/PylonVersionNumber.h \
		pylon/TransportLayer.h \
		pylon/Interface.h \
		pylon/TlFactory.h \
		pylon/EventAdapter.h \
		pylon/Callback.h \
		pylon/Device.h \
		pylon/WaitObject.h \
		pylon/WaitObjects.h \
		pylon/StreamGrabber.h \
		pylon/PixelType.h \
		pylon/Pixel.h \
		pylon/PixelTypeMapper.h \
		GenApi/IEnumerationT.h \
		GenApi/Compatibility.h \
		pylon/Result.h \
		pylon/PayloadType.h \
		pylon/ResultImage.h \
		pylon/Image.h \
		pylon/SharedByteBuffer.h \
		pylon/PylonDataComponent.h \
		pylon/PylonDataContainer.h \
		pylon/ChunkParser.h \
		pylon/EventGrabber.h \
		pylon/EventGrabberProxy.h \
		pylon/NodeMapProxy.h \
		pylon/AcquireSingleFrameConfiguration.h \
		pylon/InstantCamera.h \
		pylon/ImageEventHandler.h \
		pylon/GrabResultPtr.h \
		pylon/GrabResultData.h \
		pylon/ConfigurationEventHandler.h \
		pylon/CameraEventHandler.h \
		pylon/BufferFactory.h \
		pylon/SfncVersion.h \
		pylon/ECleanup.h \
		pylon/ERegistrationMode.h \
		pylon/ETimeoutHandling.h \
		pylon/_InstantCameraParams.h \
		pylon/ParameterIncludes.h \
		pylon/ArrayParameter.h \
		pylon/Parameter.h \
		pylon/BooleanParameter.h \
		pylon/CommandParameter.h \
		pylon/EnumParameter.h \
		pylon/FloatParameter.h \
		pylon/IntegerParameter.h \
		pylon/StringParameter.h \
		pylon/EnumParameterT.h \
		pylon/ConfigurationHelper.h \
		pylon/InstantCameraArray.h \
		pylon/AcquireContinuousConfiguration.h \
		pylon/SoftwareTriggerConfiguration.h \
		pylon/InstantInterface.h \
		pylon/_BaslerUniversalInterfaceParams.h \
		pylon/PylonUtilityIncludes.h \
		pylon/PylonUtility.h \
		pylon/PylonImage.h \
		pylon/PylonImageBase.h \
		pylon/ReusableImage.h \
		pylon/ImagePersistence.h \
		pylon/PixelData.h \
		pylon/PylonImageUserBufferEventHandler.h \
		pylon/ImageDecompressor.h \
		pylon/ImageFormatConverter.h \
		pylon/_ImageFormatConverterParams.h \
		pylon/FeaturePersistence.h \
		pylon/VideoWriter.h \
		pylon/_VideoWriterParams.h \
		pylon/BaslerUniversalInstantCamera.h \
		pylon/_BaslerUniversalCameraParams.h \
		pylon/_BaslerUniversalStreamParams.h \
		pylon/_BaslerUniversalEventParams.h \
		pylon/_BaslerUniversalTLParams.h \
		pylon/BaslerUniversalConfigurationEventHandler.h \
		pylon/BaslerUniversalImageEventHandler.h \
		pylon/BaslerUniversalGrabResultPtr.h \
		pylon/BaslerUniversalGrabResultData.h \
		pylon/_BaslerUniversalChunkDataParams.h \
		pylon/private/DeviceSpecificGrabResultPtr.h \
		pylon/BaslerUniversalCameraEventHandler.h \
		pylon/private/DeviceSpecificInstantCamera.h \
		pylon/private/DeviceSpecificConfigurationEventHandlerTie.h \
		pylon/private/DeviceSpecificImageEventHandlerTie.h \
		pylon/private/DeviceSpecificCameraEventHandlerTie.h \
		pylon/gige/PylonGigEDevice.h \
		pylon/gige/PylonGigE.h \
		sendimg_s.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sqlsend.o sqlsend.cpp

sendimg.o: sendimg.cpp sendimg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sendimg.o sendimg.cpp

rulersettings.o: rulersettings.cpp rulersettings.h \
		ui_rulersettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rulersettings.o rulersettings.cpp

sendimg_s.o: sendimg_s.cpp sendimg_s.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sendimg_s.o sendimg_s.cpp

gamma_1.o: gamma_1.cpp gamma_1.h \
		ui_gamma_1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gamma_1.o gamma_1.cpp

guicamera.o: guicamera.cpp guicamera.h \
		pylon/PylonIncludes.h \
		pylon/Platform.h \
		pylon/PylonLinkage.h \
		GenICamVersion.h \
		_GenICamVersion.h \
		Base/GCLinkage.h \
		Base/GCTypes.h \
		Base/GCNamespace.h \
		Base/GCString.h \
		Base/GCStringVector.h \
		GenApi/GenApi.h \
		Base/GCBase.h \
		Base/GCArray.h \
		Base/GCException.h \
		Base/GCCompatibility.h \
		Base/GCUtilities.h \
		Base/GCRTSSUtilities.h \
		GenApi/GenApiDll.h \
		GenApi/GenApiNamespace.h \
		GenApi/Pointer.h \
		GenICamFwd.h \
		GenApi/IEnumeration.h \
		GenApi/IEnumEntry.h \
		GenApi/IValue.h \
		GenApi/Types.h \
		GenApi/Autovector.h \
		GenApi/IBase.h \
		GenApi/Reference.h \
		GenApi/INode.h \
		GenApi/Container.h \
		GenApi/IFloat.h \
		GenApi/IInteger.h \
		GenApi/ICategory.h \
		GenApi/IRegister.h \
		GenApi/IBoolean.h \
		GenApi/IPort.h \
		GenApi/IPortStacked.h \
		GenApi/IPortRecorder.h \
		GenApi/IPortConstruct.h \
		GenApi/IChunkPort.h \
		GenApi/IString.h \
		GenApi/INodeMap.h \
		GenApi/Synch.h \
		GenApi/ConcatenatedWrite.h \
		GenApi/IDestroy.h \
		GenApi/IDeviceInfo.h \
		GenApi/ISelector.h \
		GenApi/ICommand.h \
		GenApi/IUserData.h \
		GenApi/NodeMapRef.h \
		GenApi/NodeMapFactory.h \
		GenApi/GenApiVersion.h \
		GenApi/NodeCallback.h \
		GenApi/Persistence.h \
		GenApi/SelectorSet.h \
		GenApi/ISelectorDigit.h \
		GenApi/SelectorState.h \
		GenApi/StructPort.h \
		GenApi/PortImpl.h \
		GenApi/GenApiLinkage.h \
		pylon/stdinclude.h \
		pylon/TypeMappings.h \
		pylon/PylonBase.h \
		pylon/PylonVersionInfo.h \
		pylon/Info.h \
		pylon/TlInfo.h \
		pylon/DeviceClass.h \
		pylon/DeviceInfo.h \
		pylon/Container.h \
		pylon/InterfaceInfo.h \
		pylon/StaticDefectPixel.h \
		pylon/DeviceFactory.h \
		pylon/DeviceAccessMode.h \
		pylon/PylonVersionNumber.h \
		pylon/TransportLayer.h \
		pylon/Interface.h \
		pylon/TlFactory.h \
		pylon/EventAdapter.h \
		pylon/Callback.h \
		pylon/Device.h \
		pylon/WaitObject.h \
		pylon/WaitObjects.h \
		pylon/StreamGrabber.h \
		pylon/PixelType.h \
		pylon/Pixel.h \
		pylon/PixelTypeMapper.h \
		GenApi/IEnumerationT.h \
		GenApi/Compatibility.h \
		pylon/Result.h \
		pylon/PayloadType.h \
		pylon/ResultImage.h \
		pylon/Image.h \
		pylon/SharedByteBuffer.h \
		pylon/PylonDataComponent.h \
		pylon/PylonDataContainer.h \
		pylon/ChunkParser.h \
		pylon/EventGrabber.h \
		pylon/EventGrabberProxy.h \
		pylon/NodeMapProxy.h \
		pylon/AcquireSingleFrameConfiguration.h \
		pylon/InstantCamera.h \
		pylon/ImageEventHandler.h \
		pylon/GrabResultPtr.h \
		pylon/GrabResultData.h \
		pylon/ConfigurationEventHandler.h \
		pylon/CameraEventHandler.h \
		pylon/BufferFactory.h \
		pylon/SfncVersion.h \
		pylon/ECleanup.h \
		pylon/ERegistrationMode.h \
		pylon/ETimeoutHandling.h \
		pylon/_InstantCameraParams.h \
		pylon/ParameterIncludes.h \
		pylon/ArrayParameter.h \
		pylon/Parameter.h \
		pylon/BooleanParameter.h \
		pylon/CommandParameter.h \
		pylon/EnumParameter.h \
		pylon/FloatParameter.h \
		pylon/IntegerParameter.h \
		pylon/StringParameter.h \
		pylon/EnumParameterT.h \
		pylon/ConfigurationHelper.h \
		pylon/InstantCameraArray.h \
		pylon/AcquireContinuousConfiguration.h \
		pylon/SoftwareTriggerConfiguration.h \
		pylon/InstantInterface.h \
		pylon/_BaslerUniversalInterfaceParams.h \
		pylon/PylonUtilityIncludes.h \
		pylon/PylonUtility.h \
		pylon/PylonImage.h \
		pylon/PylonImageBase.h \
		pylon/ReusableImage.h \
		pylon/ImagePersistence.h \
		pylon/PixelData.h \
		pylon/PylonImageUserBufferEventHandler.h \
		pylon/ImageDecompressor.h \
		pylon/ImageFormatConverter.h \
		pylon/_ImageFormatConverterParams.h \
		pylon/FeaturePersistence.h \
		pylon/VideoWriter.h \
		pylon/_VideoWriterParams.h \
		pylon/BaslerUniversalInstantCamera.h \
		pylon/_BaslerUniversalCameraParams.h \
		pylon/_BaslerUniversalStreamParams.h \
		pylon/_BaslerUniversalEventParams.h \
		pylon/_BaslerUniversalTLParams.h \
		pylon/BaslerUniversalConfigurationEventHandler.h \
		pylon/BaslerUniversalImageEventHandler.h \
		pylon/BaslerUniversalGrabResultPtr.h \
		pylon/BaslerUniversalGrabResultData.h \
		pylon/_BaslerUniversalChunkDataParams.h \
		pylon/private/DeviceSpecificGrabResultPtr.h \
		pylon/BaslerUniversalCameraEventHandler.h \
		pylon/private/DeviceSpecificInstantCamera.h \
		pylon/private/DeviceSpecificConfigurationEventHandlerTie.h \
		pylon/private/DeviceSpecificImageEventHandlerTie.h \
		pylon/private/DeviceSpecificCameraEventHandlerTie.h \
		pylon/gige/PylonGigEDevice.h \
		pylon/gige/PylonGigE.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guicamera.o guicamera.cpp

moc_light.o: moc_light.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_light.o moc_light.cpp

moc_camera.o: moc_camera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camera.o moc_camera.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_pfs.o: moc_pfs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pfs.o moc_pfs.cpp

moc_rgb.o: moc_rgb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rgb.o moc_rgb.cpp

moc_deal.o: moc_deal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_deal.o moc_deal.cpp

moc_drawview.o: moc_drawview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_drawview.o moc_drawview.cpp

moc_rulebar.o: moc_rulebar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rulebar.o moc_rulebar.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_sqlsend.o: moc_sqlsend.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sqlsend.o moc_sqlsend.cpp

moc_sendimg.o: moc_sendimg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sendimg.o moc_sendimg.cpp

moc_rulersettings.o: moc_rulersettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rulersettings.o moc_rulersettings.cpp

moc_sendimg_s.o: moc_sendimg_s.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sendimg_s.o moc_sendimg_s.cpp

moc_gamma_1.o: moc_gamma_1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gamma_1.o moc_gamma_1.cpp

moc_guicamera.o: moc_guicamera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_guicamera.o moc_guicamera.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/blaser_app/bin || mkdir -p $(INSTALL_ROOT)/opt/blaser_app/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/blaser_app/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/blaser_app/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/blaser_app/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/blaser_app/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

