//-----------------------------------------------------------------------------
//  Basler Data Processing SDK
//  Copyright (c) 2021-2025 Basler AG
//  http://www.baslerweb.com
//  Author:  BR
//-----------------------------------------------------------------------------
//
// This file is autogenerated. Changes will be overwritten.
// File contains pylon data processing version defines.

#pragma once

#define PYLON_DATAPROCESSING_VERSION_MAJOR           3
#define PYLON_DATAPROCESSING_VERSION_MINOR           5
#define PYLON_DATAPROCESSING_VERSION_SUBMINOR        2
#define PYLON_DATAPROCESSING_VERSION_BUILD           9054

#define PYLON_DATAPROCESSING_VERSIONSTRING_MAJOR     "3"
#define PYLON_DATAPROCESSING_VERSIONSTRING_MINOR     "5"
#define PYLON_DATAPROCESSING_VERSIONSTRING_SUBMINOR  "2"
#define PYLON_DATAPROCESSING_VERSIONSTRING_BUILD     "9054"
#define PYLON_DATAPROCESSING_VERSIONSTRING_EXTENSION "9054"

#define PYLON_DATAPROCESSING_GIT_REVISION            "2a98e1fd37d7e4fec51bf30be77acb882ea326cf"
#define PYLON_DATAPROCESSING_VERSION_SUFFIX          "_v3"
